# Generated by Django 5.2.7 on 2025-11-10 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboardstat_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardstat',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='dashboardstat',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dashboardstat',
            name='value',
            field=models.IntegerField(),
        ),
    ]
